### PR TITLE
Addition of horizontal scroll and vertical scroll

### PR DESCRIPTION
**Pull request by murata2makoto**
I created two example EPUB publications for vertically scrollable manga and horizontally scrollable emakimono (horizontal, illustrated narrative form created during the 11th to 16th centuries in Japan).

### CODE REVIEW

**Comment by danielweck** [comment]
Thanks @murata0204 !
Note that there is a typo in "horiozntally-scrollable-emakimono" (should be "horizontally")

**Comment by danielweck** [comment]
cc @rkwright

Just out of curiosity, I loaded your EPUBs into the Readium "cloud / web reader", directly from your GitHub repository URL.

Unsurprisingly, horizontal scrolling does not work, as this feature is not implemented:

https://readium.firebaseapp.com/?epub=https%3A%2F%2Frawgit.com%2Fmurata0204%2Fepub3-samples%2Fmaster%2F30%2Fhoriozntally-scrollable-emakimono
(from https://github.com/murata0204/epub3-samples/tree/master/30/horiozntally-scrollable-emakimono )

Vertical scrolling seems to work fine though (please check):

https://readium.firebaseapp.com/?epub=https%3A%2F%2Frawgit.com%2Fmurata0204%2Fepub3-samples%2Fmaster%2F30%2Fvertically-scrollable-manga
(from https://github.com/murata0204/epub3-samples/tree/master/30/vertically-scrollable-manga )

**Comment by danielweck** [comment]
Interestingly, the EPUB3+ specification seems to explicitly forbid the use of scrolling rendition properties in fixed layout content. Am I right?

http://www.idpf.org/epub/31/spec/epub-packages.html#layout-property-flow

```
If a Reading Systems supports the rendition:layout property,
it must ignore the rendition:flow property when it has been set on a spine item
that also specifies the rendition:layout value pre-paginated.
```

**Comment by murata2makoto** [comment]
Thanks, Daniel.  I changed the directory name.

**Comment by murata2makoto** [comment]
[Creating Vertically Scrollable Manga
](https://docs.google.com/document/d/1_mab1YECyJegt5oZF8PmJl2RxZqcgPui4gnPksJ4yoA/edit#heading=h.krwuslpy0ros)
[How to Support Vertically-Scrollable EPUB Manga](https://docs.google.com/document/d/1lPDFOpxet3Plt82ginR5D4LEiJ2FPjr07pRDb_wyjH4/edit#)

**Pull request merged**
